
[package]
name = "tobkcilc"
edition = "2021"
version = "0.1.0"

[dependencies]
lazy_static = { version = "1.4.0" }
esp-idf-hal = { version = "0.41", default-features = false }
esp-idf-svc = { version = "0.46", default-features = false }
esp-idf-sys = { version = "0.33", default-features = false }
anyhow = { version = "1.0.75", default-features = false }
log = { version = "0.4", default-features = false }
esp32-nimble = "0.2.2"
hashbrown = "0.11.2"

[package.metadata.esp-idf-sys]
esp_idf_version = "tag:v4.4.6"

# [profile.release]
# debug = true

[build-dependencies]
embuild = "0.31.4"
