#!/usr/bin/osascript

tell application "System Events"
    tell application "System Preferences"
        reveal pane id "com.apple.preference.sound"
        delay 1
    end tell
    delay 1
    tell application process "System Preferences"
        click tab group 1 of window "Sound"
        delay 1
        click radio button "Output" of tab group 1 of window "Sound"
        delay 1
        set theRows to rows of table 1 of scroll area 1 of tab group 1 of window "Sound"
        repeat with theRow in theRows
            if value of text field 1 of theRow as text is equal to "Bakrum" then
                select theRow
                exit repeat
            end if
        end repeat
    end tell
    quit application "System Preferences"
end tell

