[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash -b 921600 -p /dev/cu.wchusbserial10 --monitor"
rustflags = ["-C", "default-linker-libraries", "-Z", "macro-backtrace", "--cfg", "espidf_time64"]

[unstable]
build-std = ["core", "panic_abort", "alloc"]

[env]
RUST_BACKTRACE = "1"
