[build]
target = "xtensa-esp32-espidf"

[target.riscv32imc-esp-espidf]
runner = "espflash flash -b 921600 --monitor"
rustflags = ["-C", "default-linker-libraries", "-Z", "macro-backtrace"]
linker = "ldproxy"

[target.xtensa-esp32-espidf]
runner = "espflash flash -b 921600 --monitor"
rustflags = ["-C", "default-linker-libraries", "-Z", "macro-backtrace"]
linker = "ldproxy"

[unstable]
build-std = ["std", "panic_abort"]
