[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash -b 921600 -p /dev/cu.SLAB_USBtoUART --monitor"
# rustflags = ["-C", "default-linker-libraries", "-Z", "macro-backtrace", "--cfg", "espidf_time64"]
rustflags = ["-C", "default-linker-libraries", "-Z", "macro-backtrace"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
RUST_BACKTRACE = "1"
